package guessingGame;

import javax.swing.*;

public class Driver {

    /**
     * @description
     *  Compare the user's guess against the computer and evaluates its correctness.
     * @param userAns
     *  The user's selected number
     * @param compAns
     *  The computer's autogenerated number to be guessed
     * @param count
     *  The number of guesses made by the user
     * @return
     *  A string indicating the status of the comparison made.
     */
    public static String evaluateUserGuess(int userAns, int compAns, int count) {
        if (userAns <=0 || userAns > 100) return ("Your guess is invalid");
        else if (userAns == compAns) {
            if (count == 1) return ("That's the one!\nAnd with just one try too? That's crazy!");
            else if (count > 1 && count < 10) return ("That's the one!\nIt took you a few tries, but you got there eventually!");
            else if (count > 10) return ("That's the one!\nThat was a really hard one, huh?");
        }
        else if (userAns > compAns) return ("Your guess is too high!\nTry count: " + count);
        else return ("Your guess is too low!\nTry count: " + count);
        return ("Your guess is invalid");
    }

    public static void main (String [] args) {
        // generate computer number
        int compAns = (int) (Math.random()*100 + 1);

        int userAns = 0;

        System.out.println("The correct answer is..." + compAns + "!!");

        int count = 1;

        while (userAns != compAns) {
            String response = JOptionPane.showInputDialog(null,
                    "Enter a guess between 1 and 100", "Guessing Game", 3);
            userAns = Integer.parseInt(response);

            JOptionPane.showMessageDialog(null, "" + evaluateUserGuess(userAns, compAns, count));

            count++;
        }
    }
}
